name = "Doves"
license = "MIT"
licenselink = "https://github.com/matdotcx/deadline/blob/master/LICENSE"
description = "A typography-focused Hugo theme using Doves Type"
homepage = "https://github.com/matdotcx/deadline"
tags = ["blog", "responsive", "typography", "minimal"]
features = ["responsive", "drop caps", "dark mode"]
min_version = "0.80.0"

[author]
  name = "Diego Iaconelli"
  homepage = "https://iaconelli.org"
